### ISSUE TITLE
BEM has some thing like www.getmdl.io ?

### ISSUE THREAD

**Issue by zz** [bem-site/bem-forum-content-en#10]
Just ask.

**Comment by Guria** [comment]
There is [bem-components library](http://en.bem.info/libs/bem-components) and some community libraries. What exactly do you need?

**Comment by zxqfox** [comment]
Probably, you looking for a Showcase? https://en.bem.info/libs/bem-components/v2.2.1/showcase/

**Comment by ihorzenich** [comment]
@zz getmdl (Google Material Design Lite) is one of the many realisations of BEM-methodology. There is 2 things:
1. BEM-methology: idea, rules, etc. Without any helpful tools and frameworks. Just idea, like Agile.
2. And realisations: 
 - Yandex-way (BEM-tools, etc), 
 - Google MDL, 
 - [Lightning Design System](https://www.lightningdesignsystem.com/guidelines/markup-and-style/) also
 - and so on...

**Comment by zz** [comment]
#
