### ISSUE TITLE
Недочеты на главной

### ISSUE THREAD

**Issue by remort** [bem-site/bem-forum-content-en#44]
1. EN, RU, UK
Я подумал : "Чем, интересно в Яндексе UK english отличается от US ?" и нажал. Получил украинский 0_о. Украинский это UA.

2. Не уверен, но вероятно в UK/US english все таки надо поставить определенный артикль the перед словом domain в фразе в футере:
Jadwiga and Jacek Duniec thank you for domain!
У нас конкретный домен вот этого сайта. Он есть, он один и о нем мы пишем благодарность.

3. Совсем не уверен но если у Яцека фамилия пишется Duniec и он не из UK и не из US и даже не из UA а скорее всего из восточной европы, то U читается как У. [Дунец ?]. Яб спросил самого Яцека.

**Comment by vithar** [comment]
ISO 639-1: uk

ua это код страны.

**Comment by socketpair** [comment]
http://www.localeplanet.com/icu/uk-UA/index.html

**Comment by remort** [comment]
Формально вы правы. Но все привыкли к UA. Можно было бы написать локаль uk_UA, но это тоже неправильно и вырвиглазно.

**Comment by socketpair** [comment]
![image](https://cloud.githubusercontent.com/assets/1157412/19944101/1fd19430-a15c-11e6-8062-630f43b3088b.jpg)

**Comment by socketpair** [comment]
![image](https://cloud.githubusercontent.com/assets/1157412/19944177/86c59236-a15c-11e6-9e80-2de8e0b65e5e.jpg)

**Comment by socketpair** [comment]
Похоже что код вобще нигде не пишет никто. Такие дела.

**Comment by remort** [comment]
`.ua` это домен. Он для Украины UA. Возможно он специально взят по коду страны. А в случае данной задачи они там на сайте переключают что ? Язык переключают. Поэтому берут lang code. Все как бы правильно. Только парни взваливают на себя нелегкую ношу переучивания аудитории рунета (и не только) на правильное восприятие langcode для украины. А это неблагодарное занятие. Но истина, видимо, на этом сайте, дороже. А еще можно посмотреть на вопрос с точки зрения юзабилити. Тогда надо писать то что понятней потребителю. А это видимо действительно `Укр` или подобное, как на сайтах выше которые скорее всего деньги зарабатывают. Но это совсем не по правилам.

**Comment by remort** [comment]
О, а еще вот такое есть: `ISO 639-2/T language code	ukr`
http://www.localeplanet.com/icu/uk-UA/index.html
Кажется я нашел компромисс между правилами и юзабилити.

**Comment by ivangretsky** [comment]
Добрый день!

Не уверен, что следует писать в англоязычном форуме по-русски, но раз уж так пошло с начала этой темы, для сокрытия косяков от иноязычной публики и потому, что не нашёл аналогичной темы в форуме на RU продолжаю.

Заметил ещё пару недочётов:

1. Мобильное меню при ширине <780px не видно, пока не щёлкнешь на поле поиска.
2. На десктопе для вызова меню служит иконка "лупа", что вводит в заблуждение.
3. При переходе на англоязычный блог (https://en.bem.info/forum/?labels=news&sort=created&direction=desc) или события (https://en.bem.info/forum/?labels=news,events&sort=created&direction=desc) появляется ощущение заброшенности проекта, что может отпугивать. В обоих случаях h1=Forum. Есть ощущение, что не туда попал.

**Comment by vithar** [comment]
1. Это не меню, а карта сайта она показывается, когда заблудился и хочешь что-то найти
2. Аналогично первому пункту 
3. Да, это недоделанный раздел, но ошибки тут нет. И блог, и новости хочется показывать на форуме.

**Comment by vithar** [comment]
Не нужно писать на англоязычном форуме по-русски. Для этого есть русскоязычный форум.

**Comment by ivangretsky** [comment]
@vithar Just wanted to help a bit with UX. I still think this menu/sitemap/whatever behavior is very unexpected (maybe it is worth investing time in some user testing or at least consulting the UX engineer).
