### ISSUE TITLE
gemini навигация

### ISSUE THREAD

**Issue by Gordiievskyi** [bem-site/bem-forum-content-en#9]
Добрый день,

Подскажите пожалуйста как производить навигацию между страницами. Так сложилось что мне сначала нужно зайти на url для авторизации и потом зайти на другой где собственно уже и производить тест.
Пытался найти есть ли возможность работать в gemini с навигацией в браузере из коробки. Как я понял нету, т.к. в кол бэк возможно передать только actions и find/
Вторым вызовом suite.setUrl() поменять урл на другой не вышло.
С нестед сьютами так же не выходит. Возможно я не так их применял ниже код:

parent.setUrl('first url')
        .setCaptureElements('element');
    gemini.suite('first child', function (child) {
        //this suite captures same elements on different pages
        child.setUrl('secondUrl')
            .capture('plain');
Заранее спасибо за любую помощь.

**Comment by tadatuta** [comment]
cc @SevInf

**Comment by zxqfox** [comment]
Please, use ru.bem.info/forum/ forum for posts on russian ;-)

**Comment by mursya** [comment]
Ты в англ форуме пишешь на русском, а в русском — на английском :( Не надо так :) 
Будет круто, если этот пост перенесешь в https://ru.bem.info/forum/

**Comment by Gordiievskyi** [comment]
my apologies,
done

**Comment by Gordiievskyi** [comment]
could you delete this post?
